### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-js-package-json-intro-AjvZZg#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://normanwi-kg-tgc7noax99ajvzzg.surge.sh/) and meets the following criteria:

- [x] Start your project with [these old game files](https://gist.github.com/egillespie/61d72035cd8c2639f07db1dbe2010605)
- [x] Convert the game's CSS to Sass, using variables, functions, and nesting where appropriate
- [x] Write a `dev` script in `package.json` that auto-compiles Sass and refreshes the browser at the same time
- [x] Write a `build` script in `package.json` that lints HTML, Sass, and JavaScript files before compiling Sass files (you can use these linters: [htmlhint](https://www.npmjs.com/package/htmlhint) for HTML, [stylelint](https://www.npmjs.com/package/stylelint) and [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard#installation) for Sass, [standard](https://www.npmjs.com/package/standard) for JavaScript)
- [x] All linting problems are fixed (problems will be displayed in the terminal when you run `yarn build`)
- [x] Write a `deploy` script in `package.json` that builds the project and uploads it to Surge if there are no errors
- [x] Unnecessary files like `node_modules` and your compiled CSS do not exist in your repository
- [x] Unnecessary files like `package.json` and `yarn.lock` are not uploaded to Surge

I changed it so the clickys glow when you hover over them

**Comment by egillespie** [comment]
As expected, this is a fantastic start! The glowing clickies are a nice touch too. 🌮 I have some protips to clean up your `package.json` though:

### No need for `./node_modules/.bin/` in scripts

Node will automatically look in `./node_modules/.bin` for commands before it looks in the rest of `$PATH`. That means you can simply call `standard` instead of `./node_modules/.bin/standard`. Go ahead and remove all references to `./node_modules/.bin` in your scripts.

### No custom `.stylelint` in this project

In this project we would like you to use `stylelint-config-standard` to lint your Sass files so you get practice reading package documentation and learning how to use dependencies on your own.

Please remove `.stylelint` and update `package.json` to use `stylelint-config-standard` according to the documentation we linked to.

### Rename lint scripts

`build` implies that files are changing. Since linters simply report errors and are intended to run _before_ the build process, could you pick a different name (`lint:*` perhaps) and update `package.json` accordingly? Make sure your `build` script invokes the linters before building too!

### Use `run-s` instead of `&&`

`&&` is not cross-platform, which is why this lesson encourages you to use `run-s`. Please update your `pushout` script to use `run-s`.

### Missing HTML linting

In addition to using `stylelint-config-standard`, please introduce `htmlhint` as a linter and dev dependency to satisfy criteria 4.

### No need to escape periods in `.surgeignore`

You use `\.` in `.surgeignore` a couple of times, but Surge will understand the filenames just fine without. You can just use `.` instead.

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🌯

**Comment by lordcrekit** [comment]
Instruction dyslexia strikes again :roll_eyes:
All fixed.

**Comment by egillespie** [comment]
Nice work! Especially on being the first person to configure `stylelint-config-standard` using `.stylelintrc`. The other way you can configure `stylelint` is by placing the config directly in `package.json` (which works, but is only convenient until your config gets really big):

```json
{
  "name": "MI-449-SS17-740-js-package-json-intro-AjvZZg",
  "repository": "lordcrekit/MI-449-SS17-740-js-package-json-intro-AjvZZg",
  "license": "GPL-3.0+",
  "scripts": {
    "dev:scss": "node-sass sauce/style.scss --watch --output=comperiled/css --output-style=compressed --source-map=true",
    "dev:server": "live-server",
    "dev": "run-p build:css dev:*",
    "lint:html": "htmlhint *.html",
    "lint:lintscss": "stylelint sauce/*.scss",
    "lint:lintjs": "standard *.js",
    "lint": "run-s lint:*",
    "build:clean": "rm -rf comperiled",
    "build:css": "node-sass sauce/style.scss --output=comperiled/css --output-style=compressed --source-map=true",
    "build": "run-s lint build:*",
    "deploy:push": "surge --project . --domain https://normanwi-kg-tgc7noax99ajvzzg.surge.sh/",
    "deploy": "run-s build deploy:*"
  },
  "devDependencies": {
    "htmlhint": "^0.9.13",
    "live-server": "^1.2.0",
    "node-sass": "^4.5.2",
    "npm-run-all": "^4.0.2",
    "standard": "^10.0.2",
    "stylelint": "^7.10.1",
    "stylelint-config-standard": "^16.0.0"
  },
  "stylelint": {
    "extends": "stylelint-config-standard"
  }
}
```

The last few lines of ^that^ show what I mean. No need to change anything though, you're project looks and works great! :shipit:

**Comment by lordcrekit** [comment]
I actually didn't realize you COULD put it in the package.json lol.
I've found the config documentation on stylelint to be really confusing, I didn't see package.json mentioned anywhere
